default_language_version:
  python: python3.11
repos:
  ###########
  # GENERAL #
  ###########
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=2000"]
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args: [--remove]
      - id: mixed-line-ending
        args: [--fix, lf]
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: script-must-have-extension
      - id: shellcheck
      - id: shfmt
        args: [-sr, -i 4]
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.23.1
    hooks:
      - id: toml-sort
        files: pyproject.toml
        args: [--in-place, --ignore-case, --trailing-comma-inline-array]
  ##########
  # PYTHON #
  ##########
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: [ --config, ./linters/pyproject.toml ]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.272
    hooks:
      - id: ruff
        args: [ --config, ./linters/ruff.toml ]
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports
        types: [file]
        types_or: [python, pyi]
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==23.6.5
          - flake8-comprehensions==3.12.0
          - flake8-picky-parentheses==0.5.0
          - flake8-pyi==23.5.0
          - pep8-naming==0.13.3
          - pydoclint==0.0.10
        args: [--config, ./linters/.flake8]
        types: [file]
        types_or: [python, pyi]
  -   repo: https://github.com/terrencepreilly/darglint
      rev: v1.8.1
      hooks:
      - id: darglint
  - repo: https://github.com/jendrikseipp/vulture
    rev: "v2.7"
    hooks:
      - id: vulture
        args: ["shpyx", "tests"]
