default_language_version:
  python: python3.12
repos:
  ###########
  # GENERAL #
  ###########
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=2000"]
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args: [--remove]
      - id: mixed-line-ending
        args: [--fix, lf]
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: script-must-have-extension
      - id: shellcheck
      - id: shfmt
        args: [-sr, -i 4]
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.24.2
    hooks:
      - id: toml-sort
        files: pyproject.toml
        args: [--in-place, --ignore-case, --trailing-comma-inline-array]
  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format
        args: [--config, ./linters/taplo.toml]
      - id: taplo-lint
        args: [--config, ./linters/taplo.toml]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.0
    hooks:
      - id: yamllint
        args: ['--config-file', './linters/yamllint.yaml']
  - repo: https://github.com/biomejs/pre-commit
    rev: v1.9.4
    hooks:
      - id: biome-check
        args: [--config-path, ./linters]
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.17.3
    hooks:
      - id: cspell
        exclude: \.(csv|json|txt|lock)$
        args: ["lint", "-c", "./linters/cspell.json", "--no-progress",
               "--cache", "--cache-location", "./linters/.cspellcache"]
  ##########
  # PYTHON #
  ##########
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods
      - id: python-no-log-warn
      - id: python-use-type-annotations
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.5
    hooks:
      - id: ruff
        args: [--config, ./linters/ruff.toml]
      - id: ruff-format
        args: [--config, ./linters/ruff.toml]
  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==24.12.12
          - flake8-comprehensions==3.16.0
          - flake8-picky-parentheses==0.6.0
          - flake8-pyi==24.9.0
          - pep8-naming==0.14.1
          - pydoclint==0.6.5
        args: [--config, ./linters/.flake8]
        types: [file]
        types_or: [python, pyi]
  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.14
    hooks:
      - id: vulture
        args: ["shpyx", "tests"]
