[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
name = "shpyx"
version = "0.0.34"
description = "Run shell commands in Python"
authors = [{name = "Yossi Rozantsev"}]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.9"
keywords = ["shell", "bash", "terminal", "script"]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Libraries",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
dependencies = [
  "mypy==2.2.0",
  "pre-commit==4.3.0",
  "pytest==8.4.1",
  "pytest-cov==6.2.1",
  "pytest-mock==3.14.1",
  "ruff==0.12.8",
  "ty>=0.0.57",
]

[project.urls]
homepage = "https://github.com/Apakottur/shpyx"
repository = "https://github.com/Apakottur/shpyx"
documentation = "https://github.com/Apakottur/shpyx"

[tool.hatch.build.targets.wheel]
packages = ["shpyx"]

[tool.uv]
package = true
