# See: https://mypy.readthedocs.io/en/stable/config_file.html

[tool.mypy]
####################
# Import discovery #
####################
# Suppresses error messages about imports that cannot be resolved.
# This can be enabled per-module.
ignore_missing_imports = false

# See https://mypy.readthedocs.io/en/latest/running_mypy.html#following-imports
follow_imports = "normal"
follow_imports_for_stubs = true

##########################
# Platform configuration #
##########################
###########################
# Disallow dynamic typing #
###########################
disallow_any_unimported = true
disallow_any_expr = false
disallow_any_decorated = false
disallow_any_explicit = false
disallow_any_generics = true
disallow_subclassing_any = true
#################################
# Untyped definitions and calls #
#################################
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
##############################
# None and Optional handling #
##############################
implicit_optional = false
strict_optional = true
########################
# Configuring warnings #
########################
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_return_any = true
warn_unreachable = true
######################
# Suppressing errors #
######################
ignore_errors = false
##################################
# Miscellaneous strictness flags #
##################################
allow_untyped_globals = false
allow_redefinition = false
local_partial_types = false
# disable_error_code=
# Optional error codes: https://mypy.readthedocs.io/en/stable/error_code_list2.html
enable_error_code = [
  "redundant-self",
  "redundant-expr",
  "possibly-undefined",
  "truthy-bool",
  "truthy-iterable",
  "ignore-without-code",
  "unused-awaitable",
  "explicit-override",
]
implicit_reexport = false
strict_concatenate = true
strict_equality = true
strict = true
##############################
# Configuring error messages #
##############################
show_error_context = false
show_column_numbers = true
hide_error_codes = false
# pretty=
color_output = true
error_summary = true
show_absolute_path = false
####################
# Incremental mode #
####################
incremental = true
####################
# Advanced options #
####################
warn_incomplete_stub = true
#####################
# Report generation #
#####################
#################
# Miscellaneous #
#################
warn_unused_configs = true
# verbosity=
