name: CI

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files --show-diff

  type-checks:
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]

    name: Type Checks - Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: ./.github/workflows/util/setup_python
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run mypy
        run: uv run mypy --config-file shpyx/mypy.toml .

      - name: Run ty
        run: uv run ty check --config-file shpyx/ty.toml .

  unit-tests:
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
        os: [ubuntu-latest, windows-latest, macos-latest]

    name: Unit Tests - ${{ matrix.os }} - Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v7

      - uses: ./.github/workflows/util/setup_python
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run unit tests
        run: uv run pytest --showlocals -c tests/pytest.ini tests
