name: CI

on:
  pull_request:
    branches: [main]

  merge_group:

  workflow_dispatch:

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files --show-diff

  type-checks:
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    name: Type Checks - Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync

      - name: Run mypy
        run: uv run mypy --config-file shpyx/mypy.toml .

  unit-tests:
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        os: [ubuntu-latest, windows-latest, macos-latest]

    name: Unit Tests - ${{ matrix.os }} - Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync

      - name: Run unit tests
        run: uv run pytest --showlocals -c tests/pytest.ini tests
