name: CI

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup Python
        uses: ./.github/workflows/util/setup_python

      - name: Run pre-commit
        run: pre-commit run -v --show-diff-on-failure --color=always --all-files

  type-check:
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    name: Type Checks - Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: ./.github/workflows/util/setup_python
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run mypy
        run: mypy --config-file linters/mypy.toml .

      - name: Run ty
        run: ty check --project . --config-file linters/ty.toml

  unit-tests:
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        os: [ubuntu-latest, windows-latest, macos-latest]

    name: Unit Tests - ${{ matrix.os }} - Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7

      - uses: ./.github/workflows/util/setup_python
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run unit tests
        run: pytest --showlocals -c tests/pytest.ini tests

  check:
    name: Check All
    if: always()
    needs: [linters, type-check, unit-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
