name: Linters

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  linters:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Configure and run linters
        run: |
          sudo snap install shfmt
          python3.9 -m pip install pre-commit
          cd $GITHUB_WORKSPACE
          pre-commit run --all-files --show-diff
