# Run pre-commit via the official GitHub action.
# The action includes caching via Github cache.
# See: https://github.com/pre-commit/action
name: Linters

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  linters:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Prepare for pre-commit action
        run: |
          sudo snap install shfmt
      - uses: pre-commit/action@v2.0.2
        with:
          extra_args: --all-files --show-diff
