name: Type checks

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  mypy:
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    name: Mypy - Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: pip install poetry

      - name: Install Python dependencies
        run: poetry install

      - name: Run mypy
        run: poetry run mypy --config-file shpyx/mypy.ini .
